info = {
    title: "Bedroom",
    downloadSize: "35.0 MB",
    downloadFilename: "bedroom.zip",
    triangles: "383k",
    vertices: "192.9k",
    copyright: "&copy; 2017 fhernand",
    updatedDate: "2018-06-01",
    license: "<a href='https://creativecommons.org/licenses/by-sa/4.0/legalcode'>CC BY-SA 4.0</a>",
    description:
`<p>Generated by fhernand with RealityCapture using 546 photos (Nikon D7000, Tokina 11mm, f11, RAW format, ISO 100), after closing holes in meshes.</p>
<p>Morgan McGuire adjusted materials for OBJ.</p>
<br/>Originally published on SketchFab at <a href="https://sketchfab.com/models/869e6ec859a84240b9a099ae829f47fa#">https://sketchfab.com/models/869e6ec859a84240b9a099ae829f47fa#</a></p>`,
}
